version: '3.8'

services:

  equation-db:
    image: postgres:alpine3.18
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql:/docker-entrypoint-initdb.d